# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-08 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page1_title', models.CharField(max_length=128)),
                ('page1_subtitle', models.CharField(max_length=128)),
                ('page1_image', models.ImageField(upload_to='')),
                ('page2_title', models.CharField(max_length=128)),
                ('page2_subtitle', models.CharField(max_length=128)),
                ('page3_title', models.CharField(max_length=128)),
                ('page4_title', models.CharField(max_length=128)),
            ],
        ),
    ]
