# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-08 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='page1_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='page3_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='page4_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
