# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-08 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170108_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='page1_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='page3_service1_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page3_service1_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page3_service2_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page3_service2_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page3_service3_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page3_service3_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page3_service4_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page3_service4_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page4_address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page4_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page4_phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page4_subtitle',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='page1_title',
            field=models.CharField(help_text='Use <span> tag to highlight words', max_length=128),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='page3_title',
            field=models.CharField(blank=True, help_text='Keep this blank to remove section 3 entirely', max_length=128, null=True),
        ),
    ]
