# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-08 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170108_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page3_subtitle',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
